creation_rules:
  - path_regex: 'secrets/secrets\.yaml$'
    age: >-
      age1cr6te4rkskr9p9793ucxu3kw4f976ajwlc833540vhk252fpre2qxx9pq3,
      age1qwtm2chl4qhvranafhl9s4wv4dpg29rgl6leua0gaxef5jn8u90qq7am44
