# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  inputs,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    inputs.ucodenix.nixosModules.default
  ];

  services.ucodenix = {
    enable = true;
    cpuModelId = "auto";
  };

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "thunderbolt"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Unlock GPU overdrive/performance tuning for Radeon 860M (RDNA 3.5)
  hardware.amdgpu.overdrive.enable = true;

  services.ollama = {
    package = lib.mkForce pkgs.ollama-rocm;
    rocmOverrideGfx = lib.mkForce "11.5.0";
    loadModels = lib.mkMerge [
      [
        "qwen3.5:9b"
        "gemma4:e4b"
      ]
    ];
    environmentVariables = {
      OLLAMA_CONTEXT_LENGTH = "64000";
    };
  };
}
