# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fe8f645f-7504-469c-91ee-7be0d0f850d5";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-6e2af07e-5895-4399-8fbd-cc3b4629acda".device = "/dev/disk/by-uuid/6e2af07e-5895-4399-8fbd-cc3b4629acda";
  boot.initrd.luks.devices."luks-df483cac-8b7a-4ce9-bbb4-e589827877ca".device = "/dev/disk/by-uuid/df483cac-8b7a-4ce9-bbb4-e589827877ca";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1DDA-0D86";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/bba9f184-7980-4f52-86d2-38cf4b2885a9";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
