name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '16 6 * * 0-5' # runs everyday except on Saturday at 7:16

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v17
        with:
          inputs: nixpkgs
          pr-title: "Update flake.lock - nixpkgs" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
          token: ${{ secrets.GITHUB_TOKEN }}
