name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '16 6 * * 0-5' # runs everyday except on Saturday at 7:16

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v16
        with:
          inputs: nixpkgs
          pr-title: "Update flake.lock - nixpkgs" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated
